# NOTE: Only certain parameters are exposed here, check sample launch files for the rest
# Configuration parameters for R2D2 robot in pybullet ros simulator

#For now, please change replace your robot name in all the parameters 

robot_name: R2D2_1
    pose_x: -1.0
    pose_y: 0.0
    pose_z: 0.7
    pose_yaw: 0.0
    fixed_base: False

    # pybullet plugins, will be loaded during runtime
    # -----------------------------------------------------------------------
    # body_vel_control - Subscribe to cmd_vel and apply desired speed to the robot, without any noise
    # odometry - Query robot base pose and speed from pybullet and publish to /odom topic
    # control  - Position, velocity and effort control for all revolute joints on the robot
    # joint_state_pub - Query robot state and publish position, velocity and effort values to /joint_states
    # laser_scanner - Laser scanner simulation based on pybullet rayTestBatch function
    plugins: { pybullet_ros.plugins.body_vel_control: cmdVelCtrl,
               pybullet_ros.plugins.odometry: simpleOdometry,
               pybullet_ros.plugins.control: Control,
               pybullet_ros.plugins.joint_state_pub: joinStatePub,
               pybullet_ros.plugins.laser_scanner: laserScanner,
               pybullet_ros.plugins.rgbd_camera: RGBDCamera}

    # True = allow pybullet to compute the inertia tensor based on mass and volume of the collision shape
    # False = you can provide a more accurate inertia tensor, so inertia will be read then from URDF model
    use_intertia_from_file: False           # default: False

    # laser plugin params, default values are based on hokuyo URG-04LX-UG01
    laser:
        frame_id:           front_laser     # default: laser, laser reference frame
        angle_min:          -1.5707963      # default: -90 deg, laser field of view (fov) min angle in rad
        angle_max:          1.5707963       # default: 90 deg, overall (with prev param) we have a 180 degree fov
        num_beams:          50              # default: 512 beams for hokuyo laser
        range_min:          0.03            # default: 0.03, the minimum distance (range) that the laser is able to detect in m
        range_max:          5.6             # default: 5.6, the maximum distance (range) that the laser is able to detect in m
        beam_visualisation: False           # default: False, draw lines on pybullet gui representing the laser beams

    # rgb camera plugin parameters
    rgbd_camera:
        frame_id:           box             # default: box, the name of the reference frame of the camera
        resolution:
            width:          640             # default: 640, horizontal image resolution in pixels
            height:         480             # default: 480, vertical image resolution in pixels
